### ISSUE TITLE
Release loco-core 1.1.0

### ISSUE THREAD

**Issue by sys1yagi** [sys1yagi/loco#19]
# Changes

- [Breaking Change] Change LocoConfig interface https://github.com/sys1yagi/loco/issues/16
- implement default sender https://github.com/sys1yagi/loco/issues/12

# Todo

- [x] Upload to Bintray
- [x] Update README.md
- [x] Update Sample Code
- [x] Add tag
